# BaseGeometry.integer_validator(self, name, value)

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
>>> b = BaseGeometry()
>>> b.integer_validator("", "")
Traceback (most recent call last):
	  ...
TypeError:  must be an integer

>>> b.integer_validator("namesss", "")
Traceback (most recent call last):
	  ...
TypeError: namesss must be an integer


>>> b.integer_validator("namesss", [5])
Traceback (most recent call last):
	  ...
TypeError: namesss must be an integer


>>> b.integer_validator("namesss", 5.0)
Traceback (most recent call last):
	  ...
TypeError: namesss must be an integer


>>> b.integer_validator((), ())
Traceback (most recent call last):
	  ...
TypeError: () must be an integer


>>> b.integer_validator("ok", -3)
Traceback (most recent call last):
	  ...
ValueError: ok must be greater than 0


>>> b.integer_validator("ok", 0)
Traceback (most recent call last):
	  ...
ValueError: ok must be greater than 0


>>> b.integer_validator("namesss")
Traceback (most recent call last):
	  ...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> b.integer_validator()
Traceback (most recent call last):
	  ...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'


>>> BaseGeometry.integer_validator()
Traceback (most recent call last):
	  ...
TypeError: integer_validator() missing 3 required positional arguments: 'self', 'name', and 'value'


>>> b.integer_validator("namesss", 5, 55)
Traceback (most recent call last):
	  ...
TypeError: integer_validator() takes 3 positional arguments but 4 were given


>>> b.integer_validator("my_var", 7)


>>> b.integer_validator("my_var", 510345461354351547646354642453464634351321341)


>>> b.integer_validator((), 7)


>>> b.integer_validator("", 7)


>>> BaseGeometry.integer_validator(b, "hello", 22)




# BaseGeometry.area(self)

>>> BaseGeometry.area(b)
Traceback (most recent call last):
	  ...
Exception: area() is not implemented


>>> BaseGeometry.area()
Traceback (most recent call last):
	  ...
TypeError: area() missing 1 required positional argument: 'self'


>>> b.area(b)
Traceback (most recent call last):
	  ...
TypeError: area() takes 1 positional argument but 2 were given
